### ISSUE TITLE
Does this count punctuation?

### ISSUE THREAD

**Issue by jmanuel1** [pffy/googledocs-addon-chinese-frequency#3]
If it does, please make an option to ignore it.

**Comment by pffy** [comment]
@jmanuel1 Yes, this counts punctuation in the total count. However, punctuation is removed prior to Chinese character counts...

and, sure, we can add an option to remove punctuation from the initial total counts, too.

**Comment by jmanuel1** [comment]
I just found my actual problem! It's not with punctuation, it's vowels with tones on them - issue #4.

**Comment by jmanuel1** [comment]
I don't know whether you still want to add this feature, so I'll keep the issue open.

**Comment by pffy** [comment]
@jmanuel1 Thank you, but we will close this issue and focus on the existing bugs in issue #4 ...
