### ISSUE TITLE
Toned characters are counted as chinese characters

### ISSUE THREAD

**Issue by jmanuel1** [pffy/googledocs-addon-chinese-frequency#4]
Right now, ChineseFrequency says the following has 130 Chinese Characters.

> 他们是八个人。他们是医生，警察，宇航员（yǔháng yuán, astronaut），商人，火警员，厨师，工程师，和音乐家（yīnyuè jiā, musician）。
> 在医院医生工作。在警察局警察工作。在空间站（kōngjiānzhàn, space station）宇航员工作。在公司商人工作。在火警局火警员工作。在饭店厨师工作。在外（wài, outside）工程师工作。在公司音乐家工作。
> 他们上午（shàng wǔ, morning），中午（zhōng wǔ, afternoon），和下午（xià wǔ, evening）工作。他们工作为了（wèile, in order to）赚钱（zhuànqián, earn money）。

If you remove all 19 pinyin characters with tones:

> 他们是八个人。他们是医生，警察，宇航员（yhng yun, astronaut），商人，火警员，厨师，工程师，和音乐家（ynyu ji, musician）。
> 在医院医生工作。在警察局警察工作。在空间站（kngjinzhn, space station）宇航员工作。在公司商人工作。在火警局火警员工作。在饭店厨师工作。在外（wi, outside）工程师工作。在公司音乐家工作。
> 他们上午（shng w, morning），中午（zhng w, afternoon），和下午（xi w, evening）工作。他们工作为了（wile, in order to）赚钱（zhunqin, earn money）。

The Chinese character count becomes 111.

**Comment by pffy** [comment]
Thank you for reporting the bug! ^^ We see the same bug. We are analyzing it now.

**Comment by pffy** [comment]
@jmanuel1 Thank you for reporting the bug! ^^ We see the same bug. We are analyzing it now.

**Comment by pffy** [comment]
updated, running more tests

![screenshot-pffy-chrome-app-chinesefrequency-v6-bugfix](https://cloud.githubusercontent.com/assets/7258373/9173860/abf4c0c4-3f31-11e5-9a09-390947dad9f1.png)

**Comment by pffy** [comment]
@jmanuel1 Thank you for reporting this bug. The offline Chinese Frequency App (version 6) has been pushed out to the Chrome Web Store. 
  + https://chrome.google.com/webstore/detail/chinese-frequency-app/lkdnneogofmdkfikhbpalhelenihopga

This issue will remain open until the Google Docs Add-on is patched.

**Comment by pffy** [comment]
@jmanuel1 The latest version of the ChineseFrequency Google Docs Add-on has been pushed out to the Chrome Web Store with this bug fix. If you are using it right now, save and close your current Google Document. Then, re-open your Google Document for the add-on to be automatically updated.
